### ISSUE TITLE
use version 2.20 , have a error about the same id

### ISSUE THREAD

**Issue by fb0122** [rahatarmanahmed/CircularProgressView#37]
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.yingyonghui.market.widget.CircularProgressView$WheelSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x0. Make sure other views do not use the same id.
	at android.view.View.onRestoreInstanceState(View.java:13978)
	at android.view.View.dispatchRestoreInstanceState(View.java:13954)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3025)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3031)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3031)
	at android.view.View.restoreHierarchyState(View.java:13932)
	at android.support.v4.app.Fragment.restoreViewState(Fragment.java:466)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:981)
	at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManagerImpl.java:1314)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:730)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1501)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:490)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate$52bc874c(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:551)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:513)
	at android.support.v4.view.ViewPager.setCurrentItem$2563266(ViewPager.java:505)
	at me.xiaopan.psts.PagerSlidingTabStrip$TabViewClickListener.onClick(PagerSlidingTabStrip.java:575)
	at android.view.View.performClick(View.java:4848)
	at android.view.View$PerformClick.run(View.java:20300)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:5809)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by rahatarmanahmed** [comment]
I've gotta ask… do they have the same ID?

**Comment by rahatarmanahmed** [comment]
Also the package name shows that you are not using this library. Please open an issue with the fork you are using.

**Comment by fb0122** [comment]
OK  I know that  thank you very much
